#!/usr/bin/with-contenv bash

# make folders if required
mkdir -p \
  /config/databases \
  /config/log/mysql \
  /var/run/mysqld

# configure my.cnf and mysqld_safe
sed -i \
  -e "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" \
  -e "s|.*skip-networking.*|skip-networking|g" \
  /etc/mysql/my.cnf

sed -i \
  -e "s|.*skip-networking.*|skip-networking|g" \
  -e "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" \
  /etc/my.cnf.d/mariadb-server.cnf

sed -i "s/user='mysql'/user='abc'/g" /usr/bin/mysqld_safe

# setup custom cnf file
[[ ! -f /config/custom.cnf ]] &&
  cp /defaults/my.cnf /config/custom.cnf
[[ ! -L /etc/my.cnf.d/custom.cnf && -f /etc/my.cnf.d/custom.cnf ]] &&
  rm /etc/my.cnf.d/custom.cnf
[[ ! -L /etc/my.cnf.d/custom.cnf ]] &&
  ln -s /config/custom.cnf /etc/my.cnf.d/custom.cnf

# set permissions
chmod -R 777 \
  /var/run/mysqld
